### ISSUE TITLE
Release notes for v0.4.0 missing?

### ISSUE THREAD

**Issue by Turbo87** [tildeio/ember-element-helper#43]
It looks like the v0.4.0 has no release notes describing what was changed in this release. v0.3.2 had such notes though which is quite helpful in knowing what the breaking changes are.

**Comment by simonihmig** [comment]
Same is true for the just published 0.5.0, which actually has no breaking changes (see https://github.com/tildeio/ember-element-helper/pull/34#issuecomment-818220369). 

@chancancode can we setup `release-it` using @rwjblue's https://github.com/rwjblue/create-rwjblue-release-it-setup? I *could* provide the PR, but I cannot create the necessary labels on Github (which the script does automatically) due to permissions. So it's actually a bit easier if someone with write permissions can run `yarn create rwjblue-release-it-setup` here.

**Comment by chancancode** [comment]
Sure, @simonihmig I invited you to the repo, if there is still something that you cannot do, let me know and I can take care of it.

**Comment by chancancode** [comment]
We should also just get this accepted/implemented in glimmer-vm natively so we can stop maintaining this 😉

**Comment by simonihmig** [comment]
Thanks for the invitation! 🙏
However in this case everything (re. changelogs) seems to have been prepared already by Rob, so I'll get out of the way...
