### ISSUE TITLE
Update past embroider 0.39.x

### ISSUE THREAD

**Issue by mehulkar** [tildeio/ember-element-helper#56]
In 0.5.0, `ember-element-helper` depends on 0.39.x of the `@embroider/util`:

https://github.com/tildeio/ember-element-helper/blob/v0.5.0/package.json#L24

This version has a dependency on `broccoli-funnel` that points to a github.com address:

https://github.com/embroider-build/embroider/blob/v0.39.1/packages/util/package.json#L32

Some enterprise systems don't allow accessing github.com from inside a firewall, which means that `ember-element-helper@0.5.0` is not installable in these environments. 

Also, since this is a pre-1.0 dependency , npm treats the 0.41.0 as similar to a post-1.0 _major_ version, so it will not automatically be installed even though `^0.40.0` is specified.

See a similar issue in https://github.com/cibernox/ember-basic-dropdown/issues/616 and fix in https://github.com/cibernox/ember-basic-dropdown/commit/6e9245fe2fc29e335d95a0d0cb79734403934b06

**Comment by cibernox** [comment]
PR ready.

**Comment by snewcomer** [comment]
@chancancode Possible to get 0.5.1 published to npm when you have a moment?

**Comment by chancancode** [comment]
I tagged the release and CI was supposed to publish. However, the addon is apparently broken on canary so the publish was cancelled.

I _could_ override it with some effort (I think it’s setup so that _only_ CI can publish so I would have to regain access to the account in order to do it manually), but it’s probably better to investigate and fix whatever is going on.

If someone can run the canary ember-try scenario locally and open an issue on what they found, that would be hugely helpful. Otherwise it’s on my list to look into later in the week.

**Comment by chancancode** [comment]
Fixed in https://github.com/tildeio/ember-element-helper/commit/555d1b429ef1711b5cc8f0847698f41b75ed42f6, tagged and published v0.5.2
