### ISSUE TITLE
Broken in ember v4

### ISSUE THREAD

**Issue by knownasilya** [tildeio/ember-element-helper#72]
Getting this error

```
templateCompiler.registerPlugin is not a function
```

Can see error here https://github.com/knownasilya/ember-shadow-dom/runs/4822101357?check_suite_focus=true#step:6:171

**Comment by rwjblue** [comment]
Hmm, double check that you have the latest version of ember-cli-htmlbars (that is the thing that was using `registerPlugin`).  In order to avoid that, you need to have ember-cli-htmlbars@5.6.0 or higher (also backported to 4.x series in 4.5.0).

https://github.com/ember-cli/ember-cli-htmlbars/releases/tag/v5.6.0 has links to the related PRs

**Comment by rwjblue** [comment]
I wonder if we should bump minimums here just to ensure that we aren't bringing the older version ourselves though 🤔 

https://github.com/tildeio/ember-element-helper/blob/b368ee82de256505ffe2d39d3951abe11a206db0/package.json#L26

**Comment by knownasilya** [comment]
It's V6 in that PR.

**Comment by knownasilya** [comment]
Fixed in 0.6.0
